---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins
  namespace: dev
spec:
  resources:
    requests:
      storage: 5Gi
  accessModes:
    - ReadWriteOnce
  selector:
    matchLabels:
      app: jenkins

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins
  namespace: dev
  labels:
    app: jenkins
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  mountOptions: #NFS挂在选项
    - hard
    - nfsvers=4.1
  nfs: #NFS设置
    path: /var/opt/jenkins
    server: 172.16.0.132
