apiVersion: v1
kind: Service
metadata:
  name: jenkins
  namespace: dev
  labels:
    app: jenkins
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 8080 #服务端口
      targetPort: 8080
      nodePort: 30004 #NodePort方式暴露 Jenkins 端口
    - name: jnlp
      port: 50000 #代理端口
      targetPort: 50000
      nodePort: 30005
  selector:
    app: jenkins
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
  namespace: dev
  labels:
    app: jenkins
spec:
  selector:
    matchLabels:
      app: jenkins
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      serviceAccountName: jenkins-admin
      terminationGracePeriodSeconds: 10
      containers:
        - name: jenkins
          image: jenkins/jenkins
          securityContext:
            runAsUser: 405 #设置以ROOT用户运行容器
            privileged: true #拥有特权
          ports:
            - name: http
              containerPort: 8080
            - name: jnlp
              containerPort: 50000
          resources:
            limits:
              memory: 2Gi
              cpu: 1000Mi
            requests:
              memory: 1Gi
              cpu: 500Mi
          env:
            - name: LIMITS_MEMORY
              valueFrom:
                resourceFieldRef:
                  resource: limits.memory
                  divisor: 1Mi
            - name: "JAVA_OPTS" #设置变量，指定时区和 jenkins slave 执行者设置
              value:
                "
                -Xmx$(LIMITS_MEMORY)m
                -XshowSettings:vm
                -Dhudson.slaves.NodeProvisioner.initialDelay=0
                -Dhudson.slaves.NodeProvisioner.MARGIN=50
                -Dhudson.slaves.NodeProvisioner.MARGIN0=0.85
                -Duser.timezone=Asia/Shanghai
                "
                #-Djava.awt.headless=true
                #-Dhudson.model.DownloadService.noSignatureCheck=true
            - name: "JENKINS_OPTS"
              value: "--prefix=/jenkins" #设置路径前缀加上 Jenkins
          volumeMounts: #设置要挂在的目录
            - name: data
              mountPath: /var/jenkins_home
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: jenkins #设置PVC
