apiVersion: v1
kind: ServiceAccount
metadata:
  name: jenkins-admin #ServiceAccount名
  labels:
    name: jenkins
  namespace: dev
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: jenkins-admin
  namespace: dev
  labels:
    name: jenkins
subjects:
  - kind: ServiceAccount
    name: jenkins-admin
    namespace: dev
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
